apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30008
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: web-app-deploy
  labels:
    app: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - image: adjust:latest
        name: myapp
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: web-app
